### ISSUE TITLE
Thanks for writing!

### ISSUE THREAD

**Issue by nhooyr** [bastibe/bastibe.github.com#1]
I had to thank you after reading https://bastibe.de/2020-05-01-raw-developer-comparison.html!

It was very insightful for me and I fully agree that lightroom, darktable or ON1 make the most sense as the use of sidecar files is extremely important!

I would have emailed you but there is no email on your blog or github but I had to thank you.

**Comment by nhooyr** [comment]
I should add, for me personally darktable is unfortunately out due to no support for Canon's CR3 RAW format. They use it on the newer EOS R line which is what I use. RawTherapee does in fact support it but like you said no local edits which are important for me as well. I think I'm going to end up with lightroom anyway since I'll get photoshop as well. But I'll keep an eye on ON1 too!

I've been using affinity photo but it the lack of non destructive raw editing can be very frustrating as I have to start from scratch if I want to adjust something later on with the RAW.

**Comment by bastibe** [comment]
Thank you for reaching out to say thank you! It is a rare occurrence to receive direct feedback like that, and truly warms my heart.

AFAIK Canon CR3 support is in fact a legal issue, as the format seems to be encumbered by patents. It's a thorny issue for Open Source developers.

But there are good news with regards to local edits in RawTherapee: the next major version of RT will include local edits, and a fork of RT, called "ART", includes them now.

**Comment by nhooyr** [comment]
> Thank you for reaching out to say thank you! It is a rare occurrence to receive direct feedback like that, and truly warms my heart.

❤️ 

> AFAIK Canon CR3 support is in fact a legal issue, as the format seems to be encumbered by patents. It's a thorny issue for Open Source developers.

Ah that sucks! Had I known before I bought the camera, it might have swayed me towards Sony, Nikon or Fuji.

> But there are good news with regards to local edits in RawTherapee: the next major version of RT will include local edits, and a fork of RT, called "ART", includes them now.

Thanks for letting me know, I'll keep an eye on both RawTherapee and ART.
